export const NOTIFICATION_TYPES = {
  ORDER_PLACED: 'order_placed',
  ORDER_ACCEPTED: 'order_accepted',
  ORDER_STATUS_CHANGED: 'order_status_changed',
  ORDER_CONFIRMED: 'order_confirmed',
  ORDER_CANCELLED: 'order_cancelled',
  TENDER_CREATED: 'tender_created',
  TENDER_OFFER_RECEIVED: 'tender_offer_received',
  TENDER_OFFER_ACCEPTED: 'tender_offer_accepted',
  TENDER_OFFER_DECLINED: 'tender_offer_declined',
  CONTRACT_OFFER_RECEIVED: 'contract_offer_received',
  CONTRACT_ACCEPTED: 'contract_accepted',
  CONTRACT_DELIVERY_REMINDER: 'contract_delivery_reminder',
  CONTRACT_DELIVERY_CONFIRMED: 'contract_delivery_confirmed',
  NEW_LISTING: 'new_listing',
  LISTING_MATCH: 'listing_match',
  REVIEW_RECEIVED: 'review_received',
  FARMER_APPROVED: 'farmer_approved',
  FARMER_REJECTED: 'farmer_rejected',
  PRODUCT_REQUEST_APPROVED: 'product_request_approved',
  PRODUCT_REQUEST_REJECTED: 'product_request_rejected',
} as const;

export const NOTIFICATION_TYPE_LABELS: Record<string, string> = {
  order_placed: 'Order Placed',
  order_accepted: 'Order Accepted',
  order_status_changed: 'Order Status Changed',
  order_confirmed: 'Order Confirmed',
  order_cancelled: 'Order Cancelled',
  tender_created: 'New Tender',
  tender_offer_received: 'Tender Offer Received',
  tender_offer_accepted: 'Tender Offer Accepted',
  tender_offer_declined: 'Tender Offer Declined',
  contract_offer_received: 'Contract Offer',
  contract_accepted: 'Contract Accepted',
  contract_delivery_reminder: 'Delivery Reminder',
  contract_delivery_confirmed: 'Delivery Confirmed',
  new_listing: 'New Listing',
  listing_match: 'Listing Match',
  review_received: 'New Review',
  farmer_approved: 'Application Approved',
  farmer_rejected: 'Application Rejected',
  product_request_approved: 'Product Request Approved',
  product_request_rejected: 'Product Request Rejected',
};

export const NOTIFICATION_TYPE_ICONS: Record<string, string> = {
  order_placed: 'shopping-cart',
  order_accepted: 'check-circle',
  order_status_changed: 'refresh-cw',
  order_confirmed: 'check-square',
  order_cancelled: 'x-circle',
  tender_created: 'file-text',
  tender_offer_received: 'inbox',
  tender_offer_accepted: 'thumbs-up',
  tender_offer_declined: 'thumbs-down',
  contract_offer_received: 'file-plus',
  contract_accepted: 'check-circle',
  contract_delivery_reminder: 'clock',
  contract_delivery_confirmed: 'truck',
  new_listing: 'plus-circle',
  listing_match: 'search',
  review_received: 'star',
  farmer_approved: 'user-check',
  farmer_rejected: 'user-x',
  product_request_approved: 'check',
  product_request_rejected: 'x',
};
